name: Beau The Builder
favicon: null
layout_spectrum: 0.3434906241018325
typography_spectrum: 0.689718434587121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.21272537880577147
  lightness: 0.275645075365901
  saturation: 0.7333914237096906
  rhythmicContrast: 0.18767345091328025
purpose: []
